spring.application.name=demo2
spring.datasource.url=jdbc:mysql://localhost:3306/demo2?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
server.port=9090
spring.jpa.hibernate.ddl-auto=update
grh.app.secret=K7zR5hTmO9dWz6gQ2VnB8fLgD1cS4uYtWkC3qA0eHpJ2vLwT
grh.app.jwtExpirationMs=86400000

