package com.example.demo.Enum;

public enum natureEtude {
    INFORMATIQUE_GENERALE,
    GENIE_LOGICIEL,
    SYSTEMES_INFORMATIQUES,
    INTELLIGENCE_ARTIFICIELLE,
    RESEAUX_ET_TELECOMMUNICATIONS,
    SECURITE_INFORMATIQUE,
    SCIENCE_DES_DONNEES,
    DEVELOPPEMENT_WEB,
    DEVELOPPEMENT_MOBILE,
    CLOUD_COMPUTING

}
